# .github/workflows/ci-cd-pipeline.yml
name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 22
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'  # Vous pouvez également utiliser 'adopt' ou un autre si besoin
          java-version: '22'

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test
